version: '3'

services:
  audience-proattend-api-back:
    image: registry.coresoft-net.com/audience/proattend/api-back
    environment:
      VIRTUAL_HOST: a7m5.coresoft-dev.com

networks:
  default:
    external:
      name: docker-dev-network
