<?php

namespace Tests\Feature\Common;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use App\Models\User;

class CommonTest extends TestCase
{
    use WithoutMiddleware;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::find(1);
        $this->actingAs($this->user);
    }

    public function testMatterStatus()
    {
        $response = $this->get("api/v1/common/matter-status/all");
        $response->assertStatus(200);
    }
    public function testContractStatus()
    {
        $response = $this->get("api/v1/common/contract-status/all");
        $response->assertStatus(200);
    }

    public function testAgent()
    {
        $response = $this->get("api/v1/common/agent/all");
        $response->assertStatus(200);
    }

    public function testDashboard()
    {
        $response = $this->get("api/v1/common/dashboard");
        $response->assertStatus(200);
    }

}
