<?php

namespace Tests\Feature;

use App\Models\Interview;
use App\Models\Member;
use App\Models\TemporaryMember;
use App\Models\TemporaryMemberCareer;
use App\Models\TemporaryMemberCareerHistory;
use App\Models\TemporaryMemberEducationHistory;
use App\Models\TemporaryMemberFieldType;
use App\Models\TemporaryMemberOwnedQualification;
use App\Models\TemporaryMemberQualification;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Carbon;
use Tests\TestCase;

class TemporaryMemberTest extends TestCase
{
    use WithoutMiddleware;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $response = $this->get('/api/v1/temporary-member?name=喜嶋 知実&office_name=有限会社 田中&qualification[]=1&qualification[]=2&&owned_qualification=1');
        $response->assertStatus(200);
    }

    public function testIndex1()
    {
        $response = $this->get(route('temporary-member.index'), [
            'name' => '寺島きよみ',
        ]);
        $response = $this->get('/api/v1/temporary-member?name=寺島きよみ');
        $response->assertStatus(200);
    }

    public function testIndex2()
    {
        $response = $this->get('/api/v1/temporary-member?office_name=有限会社 田中');
        $response->assertStatus(200);
    }

    public function testIndex3()
    {
        $response = $this->get(route('temporary-member.index'), [
            'qualification' => '1'
        ]);
        $response = $this->get('/api/v1/temporary-member?qualification[]=1');
        $response->assertStatus(200);
    }

    public function testIndex4()
    {
        $response = $this->get('/api/v1/temporary-member?name=テラシマキヨミ');
        $response->assertStatus(200);
    }

    public function testIndex6()
    {
        $response = $this->get('/api/v1/temporary-member?&owned_qualification=1');
        $response->assertStatus(200);
    }


    public function testIndex5()
    {
        $response = $this->get(route('temporary-member.index'));
        $response->assertStatus(200);
    }

    public function testShow()
    {
        $response = $this->get('/api/v1/temporary-member/XXX112');
        $response->assertStatus(200);
    }

    public function testShowFailure()
    {
        $response = $this->get('/api/v1/temporary-member/999999');
        $response->assertStatus(404);
    }

    public function testDisapproval()
    {
        $model = $this->getTemporaryMember();
        $params = $model->toArray();
        $params['interview_status'] = 4;

        // 情報更新
        $response = $this->post('/api/v1/temporary-member/'. $model->member_number. '/disapproval', $params);
        $response->assertStatus(200);
        $this->assertTrue($response['interview_status'] === 4);
    }

    public function testisDisapprovalFailure()
    {
        $response = $this->post('/api/v1/temporary-member/XXX999/disapproval', []);
        $response->assertStatus(404);
    }

    public function testApproval()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $model = $this->getTemporaryMember();
        $temporaryMemberCareer = new TemporaryMemberCareer(
            [
                'temporary_member_id' => $model->id,
                'birthdate' => $faker->date(),
                'gender' => $faker->numberBetween(1,2),
                'office_name' => $faker->company(),
                'postal_code' => $faker->postcode(),
                'prefecture' => $faker->numberBetween(1,47),
                'address1' => 'XXX市YYY町',
                'address2' => '0-0-0-101',
                'tel1' => '000',
                'tel2' => '0000',
                'tel3' => '0000',
                'owned_qualifications' => '[{"qualifications":"FP2級"}]',
                'certified_accountant_number' => $faker->numberBetween(10000,99999),
                'tax_accountant_number' => $faker->numberBetween(10000,99999),
                'advisory_experience_years' => $faker->numberBetween(1,5),
                'other_specialized_field' => $faker->realText(200),
                'experience' => $faker->realText(600),
            ]
        );
        $temporaryMemberCareer->save();
        $careerHistory = new TemporaryMemberCareerHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "find_work" => "1993-09-22",
            "retirement" => "1970-05-30",
            "office_name" => "有限会社 木村",
            "status" => 1,
            "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
        ]);
        $educationHistory = new TemporaryMemberEducationHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "admission" => "1999-07-31",
            "graduation" => "1974-04-04",
            "school_name" => "原田XXX大学"
        ]);
        $fieldType = new TemporaryMemberFieldType([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "field_id" => 7,
            "type" => 1
        ]);
        $interview = new Interview([
            'temporary_member_id' => $model->id,
            "interview_candidates_time" => $faker->jobTitle(),
            "interview_fixed_time" => Carbon::now()->format('Y-m-d H:i:s'),
            "insertion_text_to_mail_template" => $faker->jobTitle(),
            "email_send_time" => Carbon::now()->format('Y-m-d H:i:s'),
            "note" => $faker->jobTitle(),
            "status" => 1,
        ]);
        $ownedQualifications = new TemporaryMemberOwnedQualification([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "owned_qualification" => $faker->numberBetween(1, 5),
            "other_qualification" => $faker->jobTitle(),
        ]);
        $careerHistory->save();
        $educationHistory->save();
        $fieldType->save();
        $interview->save();
        $ownedQualifications->Save();
        $params = $model->toArray();
        $params['interview_status'] = 5;

        // 情報更新
        $response = $this->post('/api/v1/temporary-member/'. $model->member_number.'/approval', $params);
        $response->assertStatus(200);
    }

    public function testApprovalFailure()
    {
        $response = $this->post('/api/v1/temporary-member/XXX999/approval', []);
        $response->assertStatus(404);
    }

    public function testApprovalFailure1()
    {
        $response = $this->post('/api/v1/temporary-member/XXX115/approval');
        $response->assertStatus(422);
    }

    public function testUpdate1()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3,
            "temporary_member_qualifications" => [1]
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => "20448",
            "us_certified_accountant_number" => "20448",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 1,
                    "other_qualification" => $faker->title(),
                ]
            ],
            "temporary_member_field_types" => [
                [
                    'field_id' => 1,
                    'type' => $faker->numberBetween(1, 5)
                ],
                [
                    'field_id' => 2,
                    'type' => $faker->numberBetween(1, 5)
                ]
            ],
        ];
        $response = $this->put('/api/v1/temporary-member/' . $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(200);
    }

    public function testUpdate2()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => "寺島きよみ",
            "name_furigana" => "テラシマキヨミ",
            "email" => "shuhei.kijima@example.org",
            "password" => "$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU2",
            "temporary_member_qualifications" => [1]
        ];

        $response = $this->put('/api/v1/temporary-member/'. $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(200);
    }

    public function testUpdate3()
    {
        $params = [
            "name_kanji" => "寺島きよみ",
            "name_furigana" => "ｷｼﾞﾏﾄﾓ",
            "email" => "ワタナベ.mikako@example.net",
            "password" => "$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU2",
            "temporary_member_qualifications" => [1]
        ];

        $response = $this->put('/api/v1/temporary-member/XXX112', $params);
        $response->assertStatus(200);
    }

    public function testUpdate4()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $model = $this->getTemporaryMember();
        $temporaryMemberCareer = new TemporaryMemberCareer(
            [
                'temporary_member_id' => $model->id,
                'birthdate' => $faker->date(),
                'gender' => $faker->numberBetween(1,2),
                'office_name' => $faker->company(),
                'postal_code' => $faker->postcode(),
                'prefecture' => $faker->numberBetween(1,47),
                'address1' => 'XXX市YYY町',
                'address2' => '0-0-0-101',
                'tel1' => '000',
                'tel2' => '0000',
                'tel3' => '0000',
                'owned_qualifications' => '[{"qualifications":"FP2級"}]',
                'certified_accountant_number' => $faker->numberBetween(10000,99999),
                'tax_accountant_number' => $faker->numberBetween(10000,99999),
                'advisory_experience_years' => $faker->numberBetween(1,5),
                'other_specialized_field' => $faker->realText(200),
                'experience' => $faker->realText(600),
            ]
        );
        $temporaryMemberCareer->save();
        $careerHistory = new TemporaryMemberCareerHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "find_work" => "1993-09-22",
            "retirement" => "1970-05-30",
            "office_name" => "有限会社 木村",
            "status" => 1,
            "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
        ]);
        $educationHistory = new TemporaryMemberEducationHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "admission" => "1999-07-31",
            "graduation" => "1974-04-04",
            "school_name" => "原田XXX大学"
        ]);
        $fieldType = new TemporaryMemberFieldType([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "field_id" => 7,
            "type" => 1
        ]);
        $careerHistory->save();
        $educationHistory->save();
        $fieldType->save();
        $response = $this->get('/api/v1/temporary-member/'. $model->member_number);
        $params = json_decode($response->content(), true);
        $params['temporary_member_qualifications'] = [1];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberCareer->id,
            "temporary_member_id" => $model->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => "20448",
            "us_certified_accountant_number" => "20448",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $careerHistory->id,
                    "temporary_member_career_id" => $temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $educationHistory->id,
                    "temporary_member_career_id" => $temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_field_types" => [
                [
                    'field_id' => 1,
                    'type' => $faker->numberBetween(1, 5)
                ],
                [
                    'field_id' => 2,
                    'type' => $faker->numberBetween(1, 5)
                ]
            ]
        ];

        $response = $this->put('/api/v1/temporary-member/'. $model->member_number, $params);
        $response->assertStatus(200);
    }

    public function testUpdate5()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();

        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3,
            "temporary_member_qualifications" => [1]
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => "20448",
            "us_certified_accountant_number" => "20448",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 1,
                    "other_qualification" => $faker->title(),
                ]
            ],
            "temporary_member_field_types" => [
                [
                    'field_id' => 1,
                    'type' => $faker->numberBetween(1, 5)
                ],
                [
                    'field_id' => 2,
                    'type' => $faker->numberBetween(1, 5)
                ]
            ],
        ];
        $params['temporary_member_career']["temporary_member_owned_qualifications"] = [];

        $response = $this->put('/api/v1/temporary-member/'. $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(200);
    }

    public function testUpdateFailure1()
    {
        $params = [
            "name_furigana" => "テラシマキヨミ",
            "email" => "shuhei.kijima@example.org",
            "password" => "$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU2",
            "interview_status" => 1,
        ];

        $response = $this->put('/api/v1/temporary-member/XXX112', $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure3()
    {
        $params = [
            "name_kanji" => "寺島きよみ",
            "name_furigana" => "テラシマキヨミ",
            "email" => "example.net",
            "password" => "$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU2",
            "interview_status" => 6,
        ];

        $response = $this->put('/api/v1/temporary-member/XXX112', $params);
        $response->assertStatus(422);
    }


    public function testUpdateFailure8()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $params = [
            "name_kanji" => "寺島きよみ",
            "name_furigana" => "テラシマキヨミ",
            "email" => "shuhei.kijima@example.org",
            "password" => "$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU2",
            "temporary_member_career" => [
                "id" => 95,
                "temporary_member_id" => 999999,
                "birthdate" => "1980-07-23",
                "gender" => 2,
                "office_name" => "株式会社 近藤",
                "postal_code" => "5009813",
                "prefecture" => 12,
                "address1" => "XXX市YYY町",
                "address2" => "0-0-0-101",
                "tel1" => "00",
                "tel2" => "0000",
                "tel3" => "0000",
                "owned_qualifications" => "{['qualifications':'FP2級']}",
                "certified_accountant_number" => "20448",
                "tax_accountant_number" => "40239",
                "advisory_experience_years" => 3,
                "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
                "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
                "temporary_member_career_histories" => [
                    [
                        "id" => 11,
                        "temporary_member_career_id" => 95,
                        "find_work" => "1993-09-22",
                        "retirement" => "1970-05-30",
                        "office_name" => "有限会社 木村",
                        "status" => 1,
                        "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                    ]
                ],
                "temporary_member_education_histories" => [
                    [
                        "id"=>2,
                        "temporary_member_career_id" => 95,
                        "admission" => "1999-07-31",
                        "graduation" => "1974-04-04",
                        "school_name" => "原田XXX大学"
                    ]
                ],
                "temporary_member_field_types" => [
                    [
                        'field_id' => 1,
                        'type' => $faker->numberBetween(1, 5)
                    ],
                    [
                        'field_id' => 2,
                        'type' => $faker->numberBetween(1, 5)
                    ]
                ]
            ],
        ];

        $response = $this->put('/api/v1/temporary-member/XXX112', $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure19()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => "20448",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 1,
                    "other_qualification" => 111111,
                ]
            ],
        ];
        $response = $this->put('/api/v1/temporary-member/' . $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure20()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => null,
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
                ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 1,
                    "other_qualification" => $faker->title(),
                ]
            ],
        ];
        $response = $this->put('/api/v1/temporary-member/' . $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure21()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 3,
                    "other_qualification" => $faker->title(),
                ]
            ],
        ];
        $response = $this->put('/api/v1/temporary-member/' . $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure22()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 2,
                    "other_qualification" => $faker->title(),
                ]
            ],
        ];
        $response = $this->put('/api/v1/temporary-member/' . $temporaryMemberUpdate->member_number, $params);
        $response->assertStatus(422);
    }

    public function testUpdateFailure10()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $temporaryMemberUpdate = $this->getTemporaryMemberUpdate();
        $params = [
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email(),
            "interview_status" => 3,
            "temporary_member_qualifications" => [1]
        ];
        $params['temporary_member_career'] = [
            "id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
            "temporary_member_id" => $temporaryMemberUpdate->id,
            "birthdate" => "1980-07-23",
            "gender" => 2,
            "office_name" => "株式会社 近藤",
            "postal_code" => "5009813",
            "prefecture" => 12,
            "address1" => "XXX市YYY町",
            "address2" => "0-0-0-101",
            "tel1" => "00",
            "tel2" => "0000",
            "tel3" => "0000",
            "owned_qualifications" => "{['qualifications':'FP2級']}",
            "certified_accountant_number" => "20448",
            "us_certified_accountant_number" => "20448",
            "tax_accountant_number" => "40239",
            "advisory_experience_years" => 3,
            "other_specialized_field" => "花のに気がして、手をつが埋うめんのは、そらのにあかりを見上げて不動ふどうしは高く星ぞらにひろがそっちをききました。ジョバンニはそのとこわいな音が聞こえて、きらぼうしていねえ、まるでいいながめていましたが、ちらからす」青年も誰だれが名高い高いかおるところかがやけにはいっした。汽車のなかだなや本のプラタナスのような笛ふえの ▶",
            "experience" => "るえました。たあごらんだん横よこへ行ってあっちの光るんだり、さっと白い荷物にもある美うつくしいのでしょに行くのですよ。紀元前きげんこういたわ。ほんと着きてまたくさんこう岸ぎしもこの辺へんあっちがって来ました。おまえられました。たいがら、燈台守とうが、はっぱな苹果りんのはぼく※［＃「大きなまっくりしたが、一ぺんにその黒い ▶",
            "temporary_member_career_histories" => [
                [
                    "id" => $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberCareerHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "find_work" => "1993-09-22",
                    "retirement" => "1970-05-30",
                    "office_name" => "有限会社 木村",
                    "status" => 1,
                    "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
                ]
            ],
            "temporary_member_education_histories" => [
                [
                    "id"=> $temporaryMemberUpdate->temporaryMemberCareer['temporaryMemberEducationHistories'][0]->id,
                    "temporary_member_career_id" => $temporaryMemberUpdate->temporaryMemberCareer->id,
                    "admission" => "1999-07-31",
                    "graduation" => "1974-04-04",
                    "school_name" => "原田XXX大学"
                ]
            ],
            "temporary_member_owned_qualifications" => [
                [
                    "owned_qualification" => 1,
                    "other_qualification" => $faker->title(),
                ]
            ],
            "temporary_member_field_types" => [
                [
                    'field_id' => 1,
                    'type' => $faker->numberBetween(1, 5)
                ],
                [
                    'field_id' => 2,
                    'type' => $faker->numberBetween(1, 5)
                ]
            ],
        ];

        $response = $this->put('/api/v1/temporary-member/XXX999999', $params);
        $response->assertStatus(404);
    }

    protected function getTemporaryMemberUpdate()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $model = $this->getTemporaryMember();
        $temporaryMemberCareer = new TemporaryMemberCareer(
            [
                'temporary_member_id' => $model->id,
                'birthdate' => $faker->date(),
                'gender' => $faker->numberBetween(1,2),
                'office_name' => $faker->company(),
                'postal_code' => $faker->postcode(),
                'prefecture' => $faker->numberBetween(1,47),
                'address1' => 'XXX市YYY町',
                'address2' => '0-0-0-101',
                'tel1' => '000',
                'tel2' => '0000',
                'tel3' => '0000',
                'owned_qualifications' => '[{"qualifications":"FP2級"}]',
                'certified_accountant_number' => $faker->numberBetween(10000,99999),
                'tax_accountant_number' => $faker->numberBetween(10000,99999),
                'advisory_experience_years' => $faker->numberBetween(1,5),
                'other_specialized_field' => $faker->realText(200),
                'experience' => $faker->realText(600),
            ]
        );
        $temporaryMemberCareer->save();
        $careerHistory = new TemporaryMemberCareerHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "find_work" => "1993-09-22",
            "retirement" => "1970-05-30",
            "office_name" => "有限会社 木村",
            "status" => 1,
            "free_entry" => "うか」「では、（あなんだんだから、そしてお菓子かし出されそうように見えそのひとにほんと紅べにはね、ぼくたっとは、すっかりを水銀すいて、もうすっかりにしないてごらんと水の湧わくようにして車の中へ通ったでした。「そこらはなんとつレンランの星座せいうようにそむく、水に落おち着つき当たり、ひどいったのようなよろしがみんなそんな ▶"
        ]);
        $educationHistory = new TemporaryMemberEducationHistory([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "admission" => "1999-07-31",
            "graduation" => "1974-04-04",
            "school_name" => "原田XXX大学"
        ]);
        $fieldType = new TemporaryMemberFieldType([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "field_id" => 7,
            "type" => 1
        ]);
        $ownedQualifications = new TemporaryMemberOwnedQualification([
            "temporary_member_career_id" => $temporaryMemberCareer->id,
            "owned_qualification" => $faker->numberBetween(1,3),
            "other_qualification" => $faker->title(),
        ]);
        $careerHistory->save();
        $educationHistory->save();
        $fieldType->save();
        $ownedQualifications->save();
        return $model;
    }

    protected function getTemporaryMember()
    {
        $faker = \Faker\Factory::create('ja_JP');
        $model = new TemporaryMember();
        $model->fill([
            "member_number" => substr(md5(uniqid(mt_rand(), true)), 0, 10) ,
            "name_kanji" => $faker->title(),
            "name_furigana" => $faker->title(),
            "email" => $faker->email,
            "password" => '$2y$10$0l724WL0U/AHolsPy0VPOelg9pvwdwB/NBwTvMDUPV/EHTQDscCU111',
            "interview_status" => 1
        ]);
        $model->save();

        return $model;
    }
}
